_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 53
                - 55
                - 71
                - 95
                - 105
            "2":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 53
                - 55
                - 71
                - 95
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
actor_rollout_ref:
    value:
        actor:
            clip_ratio: 0.2
            entropy_coeff: 0.001
            fsdp_config:
                fsdp_size: -1
                grad_offload: false
                optimizer_offload: false
                param_offload: false
                wrap_policy:
                    min_num_params: 0
            grad_clip: 1
            kl_loss_coef: 0.001
            kl_loss_type: low_var_kl
            optim:
                lr: 1e-06
                lr_warmup_steps_ratio: 0
                min_lr_ratio: null
                total_training_steps: 390
                warmup_style: constant
            ppo_epochs: 1
            ppo_max_token_len_per_gpu: 17408
            ppo_micro_batch_size: null
            ppo_micro_batch_size_per_gpu: null
            ppo_mini_batch_size: 256
            shuffle: false
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_dynamic_bsz: true
            use_kl_loss: true
        hybrid_engine: true
        model:
            enable_gradient_checkpointing: true
            external_lib: null
            path: /fs/archive/share/u2024001021/huggingface_models/Qwen2.5-7B-Instruct
            use_remove_padding: true
        ref:
            fsdp_config:
                param_offload: true
                wrap_policy:
                    min_num_params: 0
            log_prob_max_token_len_per_gpu: 34816
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: null
            log_prob_use_dynamic_bsz: true
            ulysses_sequence_parallel_size: 1
        rollout:
            disable_log_stats: true
            do_sample: true
            dtype: bfloat16
            enable_chunked_prefill: true
            enforce_eager: true
            free_cache_engine: true
            gpu_memory_utilization: 0.6
            ignore_eos: false
            load_format: dummy_dtensor
            log_prob_max_token_len_per_gpu: 34816
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: null
            log_prob_use_dynamic_bsz: true
            max_num_batched_tokens: 8192
            max_num_seqs: 1024
            "n": 5
            name: vllm_with_search
            prompt_length: 512
            response_length: 8192
            search_url: http://0.0.0.0:8120
            temperature: 1
            tensor_model_parallel_size: 2
            top_k: -1
            top_p: 1
algorithm:
    value:
        adv_estimator: grpo
        gamma: 1
        kl_ctrl:
            kl_coef: 0.001
            type: fixed
        kl_penalty: kl
        lam: 1
critic:
    value:
        cliprange_value: 0.5
        forward_max_token_len_per_gpu: 32768
        forward_micro_batch_size: null
        forward_micro_batch_size_per_gpu: null
        grad_clip: 1
        model:
            enable_gradient_checkpointing: true
            external_lib: null
            fsdp_config:
                fsdp_size: -1
                grad_offload: false
                optimizer_offload: false
                param_offload: false
                wrap_policy:
                    min_num_params: 0
            path: ~/models/deepseek-llm-7b-chat
            tokenizer_path: /fs/archive/share/u2024001021/huggingface_models/Qwen2.5-7B-Instruct
            use_remove_padding: false
        optim:
            lr: 1e-05
            lr_warmup_steps_ratio: 0
            min_lr_ratio: null
            total_training_steps: 390
            warmup_style: constant
        ppo_epochs: 1
        ppo_max_token_len_per_gpu: 32768
        ppo_micro_batch_size: null
        ppo_micro_batch_size_per_gpu: null
        ppo_mini_batch_size: 256
        shuffle: false
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: true
data:
    value:
        apply_chat: false
        max_prompt_length: 512
        max_response_length: 8192
        prompt_key: question
        prompt_template_name: qa_template
        return_raw_chat: false
        return_raw_input_ids: false
        save_path: /home/u2024001021/ReSearch/hotpotqa/dgt_model/rollout_result.jsonl
        shuffle: true
        tokenizer: null
        train_batch_size: 256
        train_files: /home/u2024001021/ReSearch/hotpotqa/train.parquet
        val_batch_size: 1312
        val_files: /home/u2024001021/ReSearch/hotpotqa/test.parquet
reward_model:
    value:
        enable: false
        forward_max_token_len_per_gpu: 32768
        max_length: null
        micro_batch_size: null
        micro_batch_size_per_gpu: null
        model:
            external_lib: null
            fsdp_config:
                fsdp_size: -1
                min_num_params: 0
                param_offload: false
            input_tokenizer: /fs/archive/share/u2024001021/huggingface_models/Qwen2.5-7B-Instruct
            path: ~/models/FsfairX-LLaMA3-RM-v0.1
            use_remove_padding: false
        reward_manager: qa
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: true
trainer:
    value:
        critic_warmup: 0
        default_hdfs_dir: null
        default_local_dir: /home/u2024001021/ReSearch/hotpotqa/dgt_model
        del_local_ckpt_after_load: false
        experiment_name: dgt
        logger:
            - console
            - wandb
        n_gpus_per_node: 4
        nnodes: 1
        project_name: hotpotqa
        remove_previous_ckpt_in_save: false
        resume_from_path: false
        resume_mode: auto
        save_freq: 5
        test_freq: 10
        total_epochs: 10
        total_training_steps: null
        val_before_train: true
        val_generations_to_log_to_wandb: 0
